-- Crear tablas desde cero con la nueva estructura

CREATE TABLE empresas
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo                   VARCHAR(50)                             NOT NULL,
    nombre                   VARCHAR(200)                            NOT NULL,
    nombre_comercial         VARCHAR(200),
    cedula_juridica          VARCHAR(50),
    telefono                 VARCHAR(20),
    email                    VARCHAR(100),
    direccion                TEXT,
    tipo                     VARCHAR(30),
    plan_suscripcion         VARCHAR(30),
    activa                   BOOLEAN                                 NOT NULL,
    configuracion            JSONB,
    logo_url                 VARCHAR(500),
    fecha_inicio_operaciones TIMESTAMP WITHOUT TIME ZONE,
    zona_horaria             VARCHAR(50),
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    plan                     SMALLINT,
    limite_usuarios          INTEGER,
    limite_sucursales        INTEGER,
    CONSTRAINT pk_empresas PRIMARY KEY (id)
);

CREATE TABLE sucursales
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id         BIGINT                                  NOT NULL,
    codigo             VARCHAR(50)                             NOT NULL,
    nombre             VARCHAR(200)                            NOT NULL,
    direccion          TEXT,
    telefono           VARCHAR(20),
    email              VARCHAR(100),
    es_principal       BOOLEAN,
    activa             BOOLEAN                                 NOT NULL,
    configuracion      JSONB,
    provincia          VARCHAR(10),
    canton             VARCHAR(10),
    distrito           VARCHAR(10),
    barrio             VARCHAR(50),
    otras_senas        TEXT,
    hora_apertura      time WITHOUT TIME ZONE,
    hora_cierre        time WITHOUT TIME ZONE,
    dias_operacion     VARCHAR(20),
    cantidad_mesas     INTEGER,
    capacidad_personas INTEGER,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sucursales PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                     VARCHAR(100)                            NOT NULL,
    username                  VARCHAR(50),
    password                  VARCHAR(255)                            NOT NULL,
    nombre                    VARCHAR(50)                             NOT NULL,
    apellidos                 VARCHAR(100),
    telefono                  VARCHAR(20),
    identificacion            VARCHAR(50),
    rol                       VARCHAR(30)                             NOT NULL,
    tipo_usuario              VARCHAR(20)                             NOT NULL,
    activo                    BOOLEAN                                 NOT NULL,
    bloqueado                 BOOLEAN                                 NOT NULL,
    intentos_fallidos         INTEGER DEFAULT 0,
    fecha_ultimo_intento      TIMESTAMP WITHOUT TIME ZONE,
    fecha_desbloqueo          TIMESTAMP WITHOUT TIME ZONE,
    ultimo_acceso             TIMESTAMP WITHOUT TIME ZONE,
    ultimo_cambio_password    TIMESTAMP WITHOUT TIME ZONE,
    password_temporal         BOOLEAN DEFAULT false,
    token_recuperacion        VARCHAR(255),
    fecha_token_recuperacion  TIMESTAMP WITHOUT TIME ZONE,
    foto_url                  VARCHAR(500),
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

CREATE TABLE usuarios_empresas
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id        BIGINT                                  NOT NULL,
    empresa_id        BIGINT                                  NOT NULL,
    sucursal_id       BIGINT,
    permisos          JSONB DEFAULT '{}'::jsonb,
    activo            BOOLEAN                                 NOT NULL,
    fecha_asignacion  TIMESTAMP WITHOUT TIME ZONE,
    fecha_revocacion  TIMESTAMP WITHOUT TIME ZONE,
    asignado_por      BIGINT,
    revocado_por      BIGINT,
    notas             TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuarios_empresas PRIMARY KEY (id)
);

-- Constraints únicos
ALTER TABLE empresas ADD CONSTRAINT uc_empresas_codigo UNIQUE (codigo);
ALTER TABLE sucursales ADD CONSTRAINT uc_sucursales_empresa_codigo UNIQUE (empresa_id, codigo);
ALTER TABLE usuarios ADD CONSTRAINT uc_usuarios_email UNIQUE (email);
ALTER TABLE usuarios ADD CONSTRAINT uc_usuarios_username UNIQUE (username);
ALTER TABLE usuarios_empresas ADD CONSTRAINT uk_usuario_empresa_sucursal UNIQUE (usuario_id, empresa_id, sucursal_id);

-- Foreign Keys
ALTER TABLE sucursales ADD CONSTRAINT FK_SUCURSALES_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE usuarios_empresas ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);
ALTER TABLE usuarios_empresas ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE usuarios_empresas ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ON_SUCURSAL FOREIGN KEY (sucursal_id) REFERENCES sucursales (id);

-- Índices
CREATE INDEX idx_usuarios_rol ON usuarios(rol);
CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_username ON usuarios(username);
CREATE INDEX idx_usuarios_empresas_usuario ON usuarios_empresas(usuario_id);
CREATE INDEX idx_usuarios_empresas_empresa ON usuarios_empresas(empresa_id);
CREATE INDEX idx_usuarios_empresas_sucursal ON usuarios_empresas(sucursal_id);

-- Comentarios
COMMENT ON TABLE usuarios_empresas IS 'Relación entre usuarios y empresas/sucursales donde tienen acceso';
COMMENT ON COLUMN usuarios.rol IS 'Rol global del usuario en el sistema';
COMMENT ON COLUMN usuarios_empresas.permisos IS 'Permisos específicos del usuario en esta empresa/sucursal';
COMMENT ON COLUMN usuarios.tipo_usuario IS 'Tipo de usuario: SISTEMA o EMPRESARIAL';