CREATE TABLE empresas
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo                   VARCHAR(50)                             NOT NULL,
    nombre                   VARCHAR(200)                            NOT NULL,
    nombre_comercial         VARCHAR(200),
    cedula_juridica          VARCHAR(50),
    telefono                 VARCHAR(20),
    email                    VARCHAR(100),
    direccion                TEXT,
    tipo                     VARCHAR(30),
    plan_suscripcion         VARCHAR(30),
    activa                   BOOLEAN                                 NOT NULL,
    configuracion            JSONB,
    logo_url                 VARCHAR(255),
    fecha_inicio_operaciones TIMESTAMP WITHOUT TIME ZONE,
    zona_horaria             VARCHAR(50),
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    plan                     SMALLINT,
    limite_usuarios          INTEGER,
    limite_sucursales        INTEGER,
    CONSTRAINT pk_empresas PRIMARY KEY (id)
);

CREATE TABLE sucursales
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id         BIGINT                                  NOT NULL,
    codigo             VARCHAR(50)                             NOT NULL,
    nombre             VARCHAR(200)                            NOT NULL,
    direccion          TEXT,
    telefono           VARCHAR(20),
    email              VARCHAR(100),
    es_principal       BOOLEAN,
    activa             BOOLEAN                                 NOT NULL,
    configuracion      JSONB,
    provincia          VARCHAR(10),
    canton             VARCHAR(10),
    distrito           VARCHAR(10),
    barrio             VARCHAR(50),
    otras_senas        TEXT,
    hora_apertura      time WITHOUT TIME ZONE,
    hora_cierre        time WITHOUT TIME ZONE,
    dias_operacion     VARCHAR(20),
    cantidad_mesas     INTEGER,
    capacidad_personas INTEGER,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sucursales PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                 VARCHAR(100)                            NOT NULL,
    password              VARCHAR(255)                            NOT NULL,
    nombre                VARCHAR(50)                             NOT NULL,
    apellidos             VARCHAR(100),
    telefono              VARCHAR(20),
    identificacion        VARCHAR(50),
    tipo_identificacion   VARCHAR(20),
    activo                BOOLEAN                                 NOT NULL,
    bloqueado             BOOLEAN                                 NOT NULL,
    intentos_fallidos     INTEGER,
    ultimo_acceso         TIMESTAMP WITHOUT TIME ZONE,
    fecha_cambio_password TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    bloqueado_hasta       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

CREATE TABLE usuarios_empresas_roles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id        BIGINT                                  NOT NULL,
    empresa_id        BIGINT                                  NOT NULL,
    sucursal_id       BIGINT,
    rol               VARCHAR(30)                             NOT NULL,
    permisos          JSONB,
    es_principal      BOOLEAN,
    activo            BOOLEAN                                 NOT NULL,
    fecha_asignacion  TIMESTAMP WITHOUT TIME ZONE,
    asignado_por      BIGINT,
    fecha_vencimiento TIMESTAMP WITHOUT TIME ZONE,
    notas             TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuarios_empresas_roles PRIMARY KEY (id)
);

ALTER TABLE sucursales
    ADD CONSTRAINT uc_3e319b45b2bdf601e98530d0f UNIQUE (empresa_id, codigo);

ALTER TABLE usuarios_empresas_roles
    ADD CONSTRAINT uc_ef0cd3402b2ca15cee39710c5 UNIQUE (usuario_id, empresa_id, sucursal_id);

ALTER TABLE empresas
    ADD CONSTRAINT uc_empresas_codigo UNIQUE (codigo);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_email UNIQUE (email);

ALTER TABLE sucursales
    ADD CONSTRAINT FK_SUCURSALES_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);

ALTER TABLE usuarios_empresas_roles
    ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ROLES_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);

ALTER TABLE usuarios_empresas_roles
    ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ROLES_ON_SUCURSAL FOREIGN KEY (sucursal_id) REFERENCES sucursales (id);

ALTER TABLE usuarios_empresas_roles
    ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ROLES_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

